# @package _global_

# to execute this experiment run:
# python -m run_evaluation evaluation=mbart_translation model/decoding=[mbart_generic,beam_search]

defaults:
  - override /datamodule: wmt14
  - override /model: mbart_cd
  - override /callbacks: null
  - override /trainer: gpu

# the parameters below will be merged with parameters from the default configurations set above
# this allows you to overwrite only a small/specific set of parameters
datamodule:
  debug: False

model:
  save_testing_output:
    save_log_likelihood: True

# name of the run determines folder name in logs
run_name: "mbart_translation"
