defaults:
  - decoding: [gpt_generic, beam_search]

_target_: src.models.GPT2ForGeneration

random_initialization: False
from_checkpoint: False

hf_config:
  _target_: transformers.GPT2Config.from_pretrained
  pretrained_model_name_or_path: "gpt2"
  pad_token_id: 50256

hf_model:
  pretrained_model_name_or_path: "gpt2"
  config: ${..hf_config}

tokenizer:
  _target_: transformers.GPT2Tokenizer.from_pretrained
  pretrained_model_name_or_path: "gpt2"
  padding_side: "left"
  pad_token: "<|endoftext|>"

toxicity_metric:
  _binary: True
  model_name: "original" # options: original or unbiased

save_testing_output:
  save_log_likelihood: False
