_target_: src.mdp.evaluation_models.NoisyOracleSolubility

oracle_parameters:
  device: "cuda:0"
  batch_size: 1

noising_function_parameters:
  probability_inversion: 0.2 # with 10 tokens, the Kendall's tau correlation with the original vector is  0.67 +- 0.29. Falls back to the perfect oracle for probability_inversion: 0
