# @package _global_

defaults:
  - _self_
  - datamodule: null
  - evaluation_from_file: null
  - logger: null # set to null if you don't want to use any loggers

  # debugging config (enable through command line, e.g. `python train.py debug=fast)
  - debug: null

  # enable color logging
  - /logger@logger_config: python_logger
#  - override hydra/job_logging: colorlog

wandb_run_path: ???
exp_dir: None

# verbose explanation: Hydra hijacks the working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# seed for random number generators in pytorch, numpy and python.random
seed: 123
