# @package _global_

defaults:
  - _self_
  - trainer: gpu
  - model: mbart_cd
  - datamodule: wmt14
  - callbacks: default # set to null if you don't want to use callbacks
  - logger: wandb # set to null if you don't want to use any loggers
  - hydra: training

  - training: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# set to True to run model evaluation (for cleaner logs, running evaluation using the evaluation script is preferred)
test: False

# verbose explanation: Hydra hijacks the working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# seed for random number generators in pytorch, numpy and python.random
seed: 123

# the experiment name – determines the logging folder's path
run_name: ???
