_target_: src.datamodules.RebelDataModule
num_workers: 10
pin_memory: false
seed: ${seed}

debug: false
debug_k: 12 # needs to be specified when debug is True

data_dir: ${data_dir}rebel

# Parameter that controls the quality of the matching allowed in the data
# title: allows only entities and relations with guaranteed unique textual identifiers coming from the title
# label: additionally allows for labels which could potentially not be unique to be used as identifiers (see the section covering the ID2Name dictionaries in the Demo notebook for details)
matching_status: "title" # title or label

# Ignores any samples with at least one relation that is not inside the relations_to_keep.jsonl file
relations_to_keep: ${data_dir}world_definitions/complete_relations.jsonl

# Keeps all of the samples that pass the the relations_to_keep filter, but ignores some of them
# relations_to_ignore: # ignores the relations in this file
# relation_not_to_ignore: # ignores all of the relations in the set relations_to_keep - relation_not_to_ignore

dataset_parameters:
  train:
    dataset:
      _target_: src.datamodules.RebelDataset
      seed: ${datamodule.seed}
      debug: ${datamodule.debug}
      debug_k: ${datamodule.debug_k}
      load_dataset_params:
        split: "train"
        data_dir: ${datamodule.data_dir}
        matching_status: ${datamodule.matching_status}
        relations_to_keep: ${datamodule.relations_to_keep}

    dataloader:
      batch_size: 4
      num_workers: ${datamodule.num_workers}

  val:
    dataset:
      _target_: src.datamodules.RebelDataset
      seed: ${datamodule.seed}
      debug: ${datamodule.debug}
      debug_k: ${datamodule.debug_k}
      load_dataset_params:
        split: "val"
        data_dir: ${datamodule.data_dir}
        matching_status: ${datamodule.matching_status}
        relations_to_keep: ${datamodule.relations_to_keep}

    dataloader:
      batch_size: 4
      num_workers: ${datamodule.num_workers}

  test:
    dataset:
      _target_: src.datamodules.RebelDataset
      seed: ${datamodule.seed}
      debug: ${datamodule.debug}
      debug_k: ${datamodule.debug_k}
      load_dataset_params:
        split: "test_10k"
        data_dir: ${datamodule.data_dir}
        matching_status: ${datamodule.matching_status}
        relations_to_keep: ${datamodule.relations_to_keep}

    dataloader:
      batch_size: 4
      num_workers: ${datamodule.num_workers}
