name: beam_search

hf_generation_params:
  num_beams: 5
  num_return_sequences: ${.num_beams}
  num_beam_groups: 1
  do_sample: False

  early_stopping: false

  temperature: 1.0
  length_penalty: 1.0
