defaults:
  - decoding: null # choose your decoding strategy by setting this to a decoding algorithm

hf_generation_params:
  no_repeat_ngram_size: 2
  max_length: 256
  early_stopping: false

  temperature: 1.0
  length_penalty: 1.0

seed: ${seed}
