name: mcts

defaults:
  - mcts_qtransform@hf_generation_params.mcts_qtransform: by_parent_and_siblings

hf_generation_params:
  use_cache: True
  use_mcts: True
  num_beams: 1
  num_beam_groups: 1
  num_return_sequences: 1

  mcts_debug_prints: False
  mcts_dirichlet_fraction: 0.25
  mcts_dirichlet_alpha: 0.3
  mcts_pb_c_init: 1.25
  mcts_pb_c_base: 19652
  mcts_num_simulations: 50
  mcts_topk_actions: 20
  reuse_cached_jitted_mcts: True
